Added Contributing Documentation
CommunityFocus/CommunityFocus pull request #50
Opened 2023-05-31 01:50 UTC by KhuloodHassan

## Description of the change

### Fixes # (issue that will be closed by this PR)
- Issue CommunityFocus/CommunityFocus#7

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### Changes made
- Added contributing documentation

### Screenshots/ Screenshare
- N/A

2023-06-02 20:04 UTC, nmpereira requested changes

2023-06-02 20:04 UTC, nmpereira commented on .github/CONTRIBUTING.md
> +Make changes like you would on any other project. Once you've made the chagnes and tested them thoroughly, you're ready to push changes to your fork!
```suggestion
Make changes like you would on any other project. Once you've made the changes and tested them thoroughly, you're ready to push changes to your fork!

```

2023-06-02 20:04 UTC, nmpereira commented on .github/CONTRIBUTING.md
> +7. Push your changes to your fork using `git push`
```suggestion
6. Run `npm run test` for any unit tests to run. They should all pass. If not, you need to see why the test failed and fix either the code, or update the tests to reflect your code changes.
7. Commit your changes using `git commit -m "Commit-message"`
8. Push your changes to your fork using `git push`
```

2023-06-04 06:55 UTC, KhuloodHassan commented
Revised with the changes!

2023-06-04 17:16 UTC, nmpereira approved these changes
LGTM! 🚀

2023-06-04 17:17 UTC, nmpereira commented
@KhuloodHassan Approved it. Please go ahead and merge it. I would recommend using 'squash and merge'

2023-06-05 03:26 UTC, merged